2020-06-10 00:06:20.013 [error] <0.1008.0> gen_server <0.1008.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:06:20.013 [error] <0.1008.0> CRASH REPORT Process <0.1008.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:06:20.013 [error] <0.1006.0> gen_server <0.1006.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:06:20.014 [error] <0.1006.0> CRASH REPORT Process <0.1006.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:06:20.014 [error] <0.999.0> Supervisor {<0.999.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.745>, <0.1000.0>, <0.1005.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65222 -> 127.0.0.1:5672">>) at <0.1008.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:06:20.014 [error] <0.999.0> Supervisor {<0.999.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.745>, <0.1000.0>, <0.1005.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65222 -> 127.0.0.1:5672">>) at <0.1008.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 00:06:20.014 [error] <0.997.0> gen_server <0.997.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:06:20.014 [error] <0.997.0> CRASH REPORT Process <0.997.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:06:20.014 [error] <0.995.0> Supervisor {<0.995.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.996.0>, {amqp_params_network,<<"guest">>,<<"zmNxV0CXHSAtTNAUW5Bw9fmIJtewdTfnVA7qSNtJLH6BVtus2+TNj91HeHIG4m...">>,...}) at <0.997.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:06:20.015 [error] <0.995.0> Supervisor {<0.995.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.996.0>, {amqp_params_network,<<"guest">>,<<"zmNxV0CXHSAtTNAUW5Bw9fmIJtewdTfnVA7qSNtJLH6BVtus2+TNj91HeHIG4m...">>,...}) at <0.997.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 00:06:20.015 [error] <0.1000.0> gen_server <0.1000.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:06:20.015 [error] <0.1000.0> CRASH REPORT Process <0.1000.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:06:20.015 [error] <0.996.0> Supervisor {<0.996.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.744>, <0.997.0>, <0.1003.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65221 -> 127.0.0.1:5672">>) at <0.1006.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:06:20.015 [error] <0.996.0> Supervisor {<0.996.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.744>, <0.997.0>, <0.1003.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65221 -> 127.0.0.1:5672">>) at <0.1006.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 00:06:20.016 [error] <0.998.0> Supervisor {<0.998.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.999.0>, {amqp_params_network,<<"guest">>,<<"yhmx7qE6Ml5pvAPtLNQXj/DYa8ZlARI39urY/90nKUthldJWMyozNOWM8yMA97...">>,...}) at <0.1000.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:06:20.016 [error] <0.998.0> Supervisor {<0.998.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.999.0>, {amqp_params_network,<<"guest">>,<<"yhmx7qE6Ml5pvAPtLNQXj/DYa8ZlARI39urY/90nKUthldJWMyozNOWM8yMA97...">>,...}) at <0.1000.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 00:10:53.006 [error] <0.1034.0> gen_server <0.1034.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:10:53.006 [error] <0.1034.0> CRASH REPORT Process <0.1034.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:10:53.006 [error] <0.1037.0> gen_server <0.1037.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:10:53.006 [error] <0.1037.0> CRASH REPORT Process <0.1037.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:10:53.007 [error] <0.1026.0> gen_server <0.1026.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:10:53.007 [error] <0.1026.0> CRASH REPORT Process <0.1026.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:10:53.007 [error] <0.1024.0> Supervisor {<0.1024.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1025.0>, {amqp_params_network,<<"guest">>,<<"gLaDh7MSkVNwo9MLNecf0rTVg/Ksgu6ooGIih61lRqf23SdRvL7vxf1wFVuUe2...">>,...}) at <0.1026.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:10:53.007 [error] <0.1024.0> Supervisor {<0.1024.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1025.0>, {amqp_params_network,<<"guest">>,<<"gLaDh7MSkVNwo9MLNecf0rTVg/Ksgu6ooGIih61lRqf23SdRvL7vxf1wFVuUe2...">>,...}) at <0.1026.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 00:10:53.007 [error] <0.1030.0> gen_server <0.1030.0> terminated with reason: {socket_error,timeout}
2020-06-10 00:10:53.008 [error] <0.1025.0> Supervisor {<0.1025.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.746>, <0.1026.0>, <0.1031.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65428 -> 127.0.0.1:5672">>) at <0.1034.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:10:53.008 [error] <0.1025.0> Supervisor {<0.1025.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.746>, <0.1026.0>, <0.1031.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65428 -> 127.0.0.1:5672">>) at <0.1034.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 00:10:53.008 [error] <0.1029.0> Supervisor {<0.1029.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.747>, <0.1030.0>, <0.1035.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65430 -> 127.0.0.1:5672">>) at <0.1037.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:10:53.008 [error] <0.1029.0> Supervisor {<0.1029.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.747>, <0.1030.0>, <0.1035.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65430 -> 127.0.0.1:5672">>) at <0.1037.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 00:10:53.009 [error] <0.1030.0> CRASH REPORT Process <0.1030.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 00:10:53.009 [error] <0.1028.0> Supervisor {<0.1028.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1029.0>, {amqp_params_network,<<"guest">>,<<"vNFGOUx3ZN0Y+rYR3k7kZAHHnfwzXpPZ5DkG1eecT3ZvUnaPncwiYZhFNa2eI4...">>,...}) at <0.1030.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 00:10:53.009 [error] <0.1028.0> Supervisor {<0.1028.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1029.0>, {amqp_params_network,<<"guest">>,<<"vNFGOUx3ZN0Y+rYR3k7kZAHHnfwzXpPZ5DkG1eecT3ZvUnaPncwiYZhFNa2eI4...">>,...}) at <0.1030.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 01:25:41.593 [error] <0.1070.0> gen_server <0.1070.0> terminated with reason: {socket_error,timeout}
2020-06-10 01:25:41.593 [error] <0.1066.0> gen_server <0.1066.0> terminated with reason: {socket_error,timeout}
2020-06-10 01:25:41.593 [error] <0.1070.0> CRASH REPORT Process <0.1070.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 01:25:41.593 [error] <0.1058.0> Supervisor {<0.1058.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.749>, <0.1059.0>, <0.1068.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49252 -> 127.0.0.1:5672">>) at <0.1070.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 01:25:41.594 [error] <0.1059.0> gen_server <0.1059.0> terminated with reason: {socket_error,timeout}
2020-06-10 01:25:41.594 [error] <0.1058.0> Supervisor {<0.1058.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.749>, <0.1059.0>, <0.1068.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49252 -> 127.0.0.1:5672">>) at <0.1070.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 01:25:41.594 [error] <0.1066.0> CRASH REPORT Process <0.1066.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 01:25:41.594 [error] <0.1062.0> gen_server <0.1062.0> terminated with reason: {socket_error,timeout}
2020-06-10 01:25:41.594 [error] <0.1061.0> Supervisor {<0.1061.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.748>, <0.1062.0>, <0.1064.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49251 -> 127.0.0.1:5672">>) at <0.1066.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 01:25:41.595 [error] <0.1061.0> Supervisor {<0.1061.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.748>, <0.1062.0>, <0.1064.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49251 -> 127.0.0.1:5672">>) at <0.1066.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 01:25:41.595 [error] <0.1059.0> CRASH REPORT Process <0.1059.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 01:25:41.595 [error] <0.1057.0> Supervisor {<0.1057.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1058.0>, {amqp_params_network,<<"guest">>,<<"hjFNr1Zb+CStZB2qfgGBf3AZjoZ0roVdbRzM4JbbVNIgjnq9Juj3m4foVznWLl...">>,...}) at <0.1059.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 01:25:41.595 [error] <0.1057.0> Supervisor {<0.1057.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1058.0>, {amqp_params_network,<<"guest">>,<<"hjFNr1Zb+CStZB2qfgGBf3AZjoZ0roVdbRzM4JbbVNIgjnq9Juj3m4foVznWLl...">>,...}) at <0.1059.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 01:25:41.595 [error] <0.1062.0> CRASH REPORT Process <0.1062.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 01:25:41.595 [error] <0.1060.0> Supervisor {<0.1060.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1061.0>, {amqp_params_network,<<"guest">>,<<"EvCxPjYCzznVBBcQAwOTYXxXVCYNbX5eHQMXTf+ee4RHhvDeeZRsN8/zAh3Zci...">>,...}) at <0.1062.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 01:25:41.595 [error] <0.1060.0> Supervisor {<0.1060.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1061.0>, {amqp_params_network,<<"guest">>,<<"EvCxPjYCzznVBBcQAwOTYXxXVCYNbX5eHQMXTf+ee4RHhvDeeZRsN8/zAh3Zci...">>,...}) at <0.1062.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 01:25:41.595 [error] <0.1060.0> Supervisor {<0.1060.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1061.0> exit with reason shutdown in context shutdown_error
2020-06-10 03:25:53.430 [error] <0.1088.0> gen_server <0.1088.0> terminated with reason: {socket_error,timeout}
2020-06-10 03:25:53.441 [error] <0.1099.0> gen_server <0.1099.0> terminated with reason: {socket_error,timeout}
2020-06-10 03:25:53.441 [error] <0.1091.0> gen_server <0.1091.0> terminated with reason: {socket_error,timeout}
2020-06-10 03:25:53.441 [error] <0.1095.0> gen_server <0.1095.0> terminated with reason: {socket_error,timeout}
2020-06-10 03:25:53.562 [error] <0.1095.0> CRASH REPORT Process <0.1095.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 03:25:53.564 [error] <0.1099.0> CRASH REPORT Process <0.1099.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 03:25:53.569 [error] <0.1090.0> Supervisor {<0.1090.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.751>, <0.1091.0>, <0.1097.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49523 -> 127.0.0.1:5672">>) at <0.1099.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 03:25:53.570 [error] <0.1090.0> Supervisor {<0.1090.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.751>, <0.1091.0>, <0.1097.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49523 -> 127.0.0.1:5672">>) at <0.1099.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 03:25:53.570 [error] <0.1087.0> Supervisor {<0.1087.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.750>, <0.1088.0>, <0.1093.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49522 -> 127.0.0.1:5672">>) at <0.1095.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 03:25:53.570 [error] <0.1087.0> Supervisor {<0.1087.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.750>, <0.1088.0>, <0.1093.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49522 -> 127.0.0.1:5672">>) at <0.1095.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 03:25:53.570 [error] <0.1088.0> CRASH REPORT Process <0.1088.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 03:25:53.570 [error] <0.1086.0> Supervisor {<0.1086.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1087.0>, {amqp_params_network,<<"guest">>,<<"1k3EnhzUgjDSjSKALVLzbgcysjwp7a2JmBQcunhVdLrdoDcHqpO9X6jP5Vgfwp...">>,...}) at <0.1088.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 03:25:53.570 [error] <0.1086.0> Supervisor {<0.1086.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1087.0>, {amqp_params_network,<<"guest">>,<<"1k3EnhzUgjDSjSKALVLzbgcysjwp7a2JmBQcunhVdLrdoDcHqpO9X6jP5Vgfwp...">>,...}) at <0.1088.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 03:25:53.571 [error] <0.1091.0> CRASH REPORT Process <0.1091.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 03:25:53.571 [error] <0.1089.0> Supervisor {<0.1089.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1090.0>, {amqp_params_network,<<"guest">>,<<"rq4+jKF7h8gzF1t5twtwkdRviGEchwDRDSir9XuoM+zLW8xOEJSlO3R358zl73...">>,...}) at <0.1091.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 03:25:53.571 [error] <0.1089.0> Supervisor {<0.1089.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1090.0>, {amqp_params_network,<<"guest">>,<<"rq4+jKF7h8gzF1t5twtwkdRviGEchwDRDSir9XuoM+zLW8xOEJSlO3R358zl73...">>,...}) at <0.1091.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 05:26:07.278 [error] <0.1129.0> gen_server <0.1129.0> terminated with reason: {socket_error,timeout}
2020-06-10 05:26:07.279 [error] <0.1127.0> gen_server <0.1127.0> terminated with reason: {socket_error,timeout}
2020-06-10 05:26:07.279 [error] <0.1121.0> gen_server <0.1121.0> terminated with reason: {socket_error,timeout}
2020-06-10 05:26:07.284 [error] <0.1127.0> CRASH REPORT Process <0.1127.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 05:26:07.284 [error] <0.1121.0> CRASH REPORT Process <0.1121.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 05:26:07.284 [error] <0.1117.0> Supervisor {<0.1117.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.753>, <0.1118.0>, <0.1124.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49566 -> 127.0.0.1:5672">>) at <0.1127.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 05:26:07.285 [error] <0.1117.0> Supervisor {<0.1117.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.753>, <0.1118.0>, <0.1124.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49566 -> 127.0.0.1:5672">>) at <0.1127.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 05:26:07.285 [error] <0.1118.0> gen_server <0.1118.0> terminated with reason: {socket_error,timeout}
2020-06-10 05:26:07.292 [error] <0.1118.0> CRASH REPORT Process <0.1118.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 05:26:07.308 [error] <0.1129.0> CRASH REPORT Process <0.1129.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 05:26:07.316 [error] <0.1120.0> Supervisor {<0.1120.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.752>, <0.1121.0>, <0.1126.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49565 -> 127.0.0.1:5672">>) at <0.1129.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 05:26:07.316 [error] <0.1120.0> Supervisor {<0.1120.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.752>, <0.1121.0>, <0.1126.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49565 -> 127.0.0.1:5672">>) at <0.1129.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 05:26:07.317 [error] <0.1119.0> Supervisor {<0.1119.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1120.0>, {amqp_params_network,<<"guest">>,<<"d30kDvbbSlX8S4YTks7yKOA9zhBGRhB0zFScjbgd3qs6qlNz0dzGRYpztm4nir...">>,...}) at <0.1121.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 05:26:07.317 [error] <0.1119.0> Supervisor {<0.1119.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1120.0>, {amqp_params_network,<<"guest">>,<<"d30kDvbbSlX8S4YTks7yKOA9zhBGRhB0zFScjbgd3qs6qlNz0dzGRYpztm4nir...">>,...}) at <0.1121.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 05:26:07.317 [error] <0.1116.0> Supervisor {<0.1116.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1117.0>, {amqp_params_network,<<"guest">>,<<"+MHbFfSvo8xA4ud4yYMDqd3UmItXolzNO7gT8oV/Lfe0q5d/aUEWlVQnL8eXYa...">>,...}) at <0.1118.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 05:26:07.346 [error] <0.1116.0> Supervisor {<0.1116.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1117.0>, {amqp_params_network,<<"guest">>,<<"+MHbFfSvo8xA4ud4yYMDqd3UmItXolzNO7gT8oV/Lfe0q5d/aUEWlVQnL8eXYa...">>,...}) at <0.1118.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 07:00:04.231 [error] <0.1158.0> gen_server <0.1158.0> terminated with reason: {socket_error,timeout}
2020-06-10 07:00:04.231 [error] <0.1147.0> gen_server <0.1147.0> terminated with reason: {socket_error,timeout}
2020-06-10 07:00:04.231 [error] <0.1154.0> gen_server <0.1154.0> terminated with reason: {socket_error,timeout}
2020-06-10 07:00:04.246 [error] <0.1158.0> CRASH REPORT Process <0.1158.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 07:00:04.246 [error] <0.1154.0> CRASH REPORT Process <0.1154.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 07:00:04.246 [error] <0.1150.0> gen_server <0.1150.0> terminated with reason: {socket_error,timeout}
2020-06-10 07:00:04.255 [error] <0.1149.0> Supervisor {<0.1149.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.755>, <0.1150.0>, <0.1156.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49642 -> 127.0.0.1:5672">>) at <0.1158.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 07:00:04.301 [error] <0.1149.0> Supervisor {<0.1149.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.755>, <0.1150.0>, <0.1156.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49642 -> 127.0.0.1:5672">>) at <0.1158.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 07:00:04.301 [error] <0.1146.0> Supervisor {<0.1146.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.754>, <0.1147.0>, <0.1152.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49641 -> 127.0.0.1:5672">>) at <0.1154.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 07:00:04.301 [error] <0.1146.0> Supervisor {<0.1146.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.754>, <0.1147.0>, <0.1152.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49641 -> 127.0.0.1:5672">>) at <0.1154.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 07:00:04.302 [error] <0.1150.0> CRASH REPORT Process <0.1150.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 07:00:04.312 [error] <0.1148.0> Supervisor {<0.1148.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1149.0>, {amqp_params_network,<<"guest">>,<<"FXaMR8XcRK5WJwdEicMVCKxTJqGiYg5zelK1bpkBQP+WnXLRpVX4stiEq2by9E...">>,...}) at <0.1150.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 07:00:04.313 [error] <0.1148.0> Supervisor {<0.1148.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1149.0>, {amqp_params_network,<<"guest">>,<<"FXaMR8XcRK5WJwdEicMVCKxTJqGiYg5zelK1bpkBQP+WnXLRpVX4stiEq2by9E...">>,...}) at <0.1150.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 07:00:04.313 [error] <0.1147.0> CRASH REPORT Process <0.1147.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 07:00:04.314 [error] <0.1145.0> Supervisor {<0.1145.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1146.0>, {amqp_params_network,<<"guest">>,<<"VQVQszYhkLgqSbPLjkMpzvriliJqeBmIjtpOUJCXukIBoGIMKkiTmZ32E8livp...">>,...}) at <0.1147.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 07:00:04.315 [error] <0.1145.0> Supervisor {<0.1145.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1146.0>, {amqp_params_network,<<"guest">>,<<"VQVQszYhkLgqSbPLjkMpzvriliJqeBmIjtpOUJCXukIBoGIMKkiTmZ32E8livp...">>,...}) at <0.1147.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:01:41.023 [error] <0.1180.0> gen_server <0.1180.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:01:41.024 [error] <0.1180.0> CRASH REPORT Process <0.1180.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:01:41.024 [error] <0.1187.0> gen_server <0.1187.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:01:41.025 [error] <0.1187.0> CRASH REPORT Process <0.1187.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:01:41.026 [error] <0.1175.0> Supervisor {<0.1175.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.756>, <0.1176.0>, <0.1178.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49696 -> 127.0.0.1:5672">>) at <0.1180.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:01:41.027 [error] <0.1175.0> Supervisor {<0.1175.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.756>, <0.1176.0>, <0.1178.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49696 -> 127.0.0.1:5672">>) at <0.1180.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:01:41.027 [error] <0.1183.0> gen_server <0.1183.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:01:41.028 [error] <0.1182.0> Supervisor {<0.1182.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.757>, <0.1183.0>, <0.1185.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49697 -> 127.0.0.1:5672">>) at <0.1187.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:01:41.029 [error] <0.1182.0> Supervisor {<0.1182.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.757>, <0.1183.0>, <0.1185.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49697 -> 127.0.0.1:5672">>) at <0.1187.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:01:41.029 [error] <0.1176.0> gen_server <0.1176.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:01:41.029 [error] <0.1183.0> CRASH REPORT Process <0.1183.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:01:41.029 [error] <0.1176.0> CRASH REPORT Process <0.1176.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:01:41.030 [error] <0.1181.0> Supervisor {<0.1181.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1182.0>, {amqp_params_network,<<"guest">>,<<"PJlAnxMPxRHCYByXb2jNylJB1rxa+ZOQK2wtJBPFaTHsL1rldgSSgLUA/OlSi9...">>,...}) at <0.1183.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:01:41.030 [error] <0.1181.0> Supervisor {<0.1181.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1182.0>, {amqp_params_network,<<"guest">>,<<"PJlAnxMPxRHCYByXb2jNylJB1rxa+ZOQK2wtJBPFaTHsL1rldgSSgLUA/OlSi9...">>,...}) at <0.1183.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:01:41.037 [error] <0.1174.0> Supervisor {<0.1174.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1175.0>, {amqp_params_network,<<"guest">>,<<"vjrISG+sObtRaDDngNVOwzHsx4AbWzIroED9y2gFCTbWoO3Dv3FDOrb8Dj6rg7...">>,...}) at <0.1176.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:01:41.038 [error] <0.1174.0> Supervisor {<0.1174.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1175.0>, {amqp_params_network,<<"guest">>,<<"vjrISG+sObtRaDDngNVOwzHsx4AbWzIroED9y2gFCTbWoO3Dv3FDOrb8Dj6rg7...">>,...}) at <0.1176.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:38:52.003 [error] <0.1216.0> gen_server <0.1216.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:38:52.003 [error] <0.1211.0> gen_server <0.1211.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:38:52.003 [error] <0.1216.0> CRASH REPORT Process <0.1216.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:38:52.004 [error] <0.1211.0> CRASH REPORT Process <0.1211.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:38:52.004 [error] <0.1207.0> gen_server <0.1207.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:38:52.004 [error] <0.1206.0> Supervisor {<0.1206.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.759>, <0.1207.0>, <0.1214.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49779 -> 127.0.0.1:5672">>) at <0.1216.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:38:52.004 [error] <0.1206.0> Supervisor {<0.1206.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.759>, <0.1207.0>, <0.1214.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49779 -> 127.0.0.1:5672">>) at <0.1216.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:38:52.004 [error] <0.1207.0> CRASH REPORT Process <0.1207.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:38:52.005 [error] <0.1205.0> Supervisor {<0.1205.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1206.0>, {amqp_params_network,<<"guest">>,<<"q73W2v4WSfH0T49hPuvFExFyULMkodCPQJFOZz+tEBJj7IF5vc2YFmBzlsxU3I...">>,...}) at <0.1207.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:38:52.005 [error] <0.1205.0> Supervisor {<0.1205.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1206.0>, {amqp_params_network,<<"guest">>,<<"q73W2v4WSfH0T49hPuvFExFyULMkodCPQJFOZz+tEBJj7IF5vc2YFmBzlsxU3I...">>,...}) at <0.1207.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:38:52.006 [error] <0.1203.0> Supervisor {<0.1203.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.758>, <0.1204.0>, <0.1209.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49758 -> 127.0.0.1:5672">>) at <0.1211.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:38:52.006 [error] <0.1203.0> Supervisor {<0.1203.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.758>, <0.1204.0>, <0.1209.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49758 -> 127.0.0.1:5672">>) at <0.1211.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-10 08:38:52.012 [error] <0.1204.0> gen_server <0.1204.0> terminated with reason: {socket_error,timeout}
2020-06-10 08:38:52.012 [error] <0.1204.0> CRASH REPORT Process <0.1204.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-06-10 08:38:52.017 [error] <0.1202.0> Supervisor {<0.1202.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1203.0>, {amqp_params_network,<<"guest">>,<<"16zWqIg1IGhk6ESxi8LrOXrlBl5Vg+zPYRvCfhZyPUGeGXFYETGFXvXi4VZZGI...">>,...}) at <0.1204.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-10 08:38:52.017 [error] <0.1202.0> Supervisor {<0.1202.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1203.0>, {amqp_params_network,<<"guest">>,<<"16zWqIg1IGhk6ESxi8LrOXrlBl5Vg+zPYRvCfhZyPUGeGXFYETGFXvXi4VZZGI...">>,...}) at <0.1204.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-15 15:44:47.438 [error] <0.555.0>@Elixir.Engine.MatchProducer:create_rmq_resources:95 CRASH REPORT Process <0.555.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.Engine.MatchProducer':create_rmq_resources/0 line 95
2020-06-15 15:45:20.333 [error] <0.374.0>@Elixir.Engine.MatchProducer:create_rmq_resources:95 Supervisor 'Elixir.Engine.BookingProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.BookingProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.BookingProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at undefined exit with reason no match of right hand value {error,{socket_closed_unexpectedly,'connection.start'}} in 'Elixir.Engine.MatchProducer':create_rmq_resources/0 line 95 in context start_error
2020-06-15 15:45:20.334 [error] <0.373.0> Supervisor 'Elixir.Engine.BookingProcessor.Broadway.Supervisor' had child #Ref<0.2315500060.2174484483.189737> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.Engine.BookingProcessor.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.Engine.BookingProcessor.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Engine.BookingProcessor.Broadway.Producer_0',{{badmatch,{error,{socket_closed_unexpectedly,'connection.start'}}},[{'Elixir.Engine.MatchProducer',create_rmq_resources,0,[{file,"lib/match_producer.ex"},{line,95}]},{'Elixir.Engine.MatchProducer',init,1,[{file,"lib/match_producer.ex"},{line,16}]},{'Elixir.Broadway.Producer',init,1,[{file,"lib/broadway/producer.ex"},{line,99}]},{'Elixir.GenStage',init,1,[{file,"lib/gen_stage.ex"},{line,1704}]},{gen_server,...},...]}}} in context start_error
2020-06-15 15:59:15.411 [error] <0.375.0>@Elixir.Vehicle:via_tuple:67 gen_server 'Elixir.Engine.BookingProcessor.Broadway.Producer_0' terminated with reason: bad argument in call to erlang:binary_to_integer(<<"3x9e4nX0nYCpzQFqlf7M7">>) in 'Elixir.Vehicle':via_tuple/1 line 67
2020-06-15 15:59:15.432 [error] <0.375.0>@Elixir.Vehicle:via_tuple:67 CRASH REPORT Process 'Elixir.Engine.BookingProcessor.Broadway.Producer_0' with 0 neighbours crashed with reason: bad argument in call to erlang:binary_to_integer(<<"3x9e4nX0nYCpzQFqlf7M7">>) in 'Elixir.Vehicle':via_tuple/1 line 67
2020-06-15 15:59:15.433 [error] <0.374.0>@Elixir.Vehicle:via_tuple:67 Supervisor 'Elixir.Engine.BookingProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.BookingProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.BookingProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.375.0> exit with reason bad argument in call to erlang:binary_to_integer(<<"3x9e4nX0nYCpzQFqlf7M7">>) in 'Elixir.Vehicle':via_tuple/1 line 67 in context child_terminated
2020-06-15 15:59:19.625 [error] <0.388.0> gen_server <0.388.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-06-15 15:59:19.625 [error] <0.388.0> CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-06-15 15:59:19.626 [error] <0.387.0> Supervisor {<0.387.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49816 -> 127.0.0.1:5672">>,1}) at <0.388.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-06-15 15:59:19.626 [error] <0.389.0> gen_server <0.389.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.388.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-oLy9bbSgq1MXWMSNdLpIAQ">>,2,false,<<"cars">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,[],undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"{\"id\":\"3yx5Bo9WnQBJA371ZFErb\",\"position\":{\"lat\":57.823033671417434,\"lon\":11.939164536230473}}">>}},60000]}} in gen_server2:call/3 line 346
2020-06-15 15:59:19.626 [error] <0.387.0> Supervisor {<0.387.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49816 -> 127.0.0.1:5672">>,1}) at <0.388.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:39.594 [error] <0.541.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.846.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.848.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.621 [error] <0.541.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.846.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.848.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.621 [error] <0.540.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.541.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.846.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.848.0>},60000]}} in context child_terminated
2020-08-31 10:31:39.708 [error] <0.849.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.861.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.863.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.709 [error] <0.849.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.861.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.863.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.709 [error] <0.540.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.849.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.861.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.863.0>},60000]}} in context child_terminated
2020-08-31 10:31:39.808 [error] <0.864.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.876.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.878.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.808 [error] <0.864.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.876.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.878.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.810 [error] <0.540.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.864.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.876.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.878.0>},60000]}} in context child_terminated
2020-08-31 10:31:39.810 [error] <0.540.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.864.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:39.811 [error] <0.539.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79072> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.Engine.AdminProcessor.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.540.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:39.880 [error] <0.880.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.994.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.996.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.881 [error] <0.880.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.994.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.996.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.882 [error] <0.879.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.880.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.994.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.996.0>},60000]}} in context child_terminated
2020-08-31 10:31:39.951 [error] <0.997.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1009.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1011.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.951 [error] <0.997.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1009.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1011.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:39.952 [error] <0.879.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.997.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1009.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1011.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.032 [error] <0.1012.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1024.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1026.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.032 [error] <0.1012.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1024.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1026.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.033 [error] <0.879.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1012.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1024.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1026.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.034 [error] <0.879.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1012.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:40.034 [error] <0.539.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79072> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.Engine.AdminProcessor.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.879.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:40.104 [error] <0.1028.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1142.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1144.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.106 [error] <0.1028.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1142.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1144.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.106 [error] <0.1027.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1028.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1142.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1144.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.165 [error] <0.1145.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1157.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1159.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.166 [error] <0.1145.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1157.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1159.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.167 [error] <0.1027.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1145.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1157.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1159.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.228 [error] <0.1160.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1172.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1174.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.228 [error] <0.1160.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1172.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1174.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.229 [error] <0.1027.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1160.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1172.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1174.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.229 [error] <0.1027.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1160.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:40.230 [error] <0.539.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79072> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.Engine.AdminProcessor.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.1027.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:40.293 [error] <0.1176.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1290.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1292.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.294 [error] <0.1176.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1290.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1292.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.295 [error] <0.1175.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1176.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1290.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1292.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.353 [error] <0.1293.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1305.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1307.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.354 [error] <0.1293.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1305.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1307.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.355 [error] <0.1175.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1293.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1305.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1307.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.410 [error] <0.1308.0> gen_server 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1320.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1322.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.412 [error] <0.1308.0> CRASH REPORT Process 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1320.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1322.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:40.412 [error] <0.1175.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1308.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'dispatch_offers' in vhost '/'">>}},{gen_server,call,[<0.1320.0>,{subscribe,{'basic.consume',0,<<"dispatch_offers">>,<<>>,false,false,false,false,[]},<0.1322.0>},60000]}} in context child_terminated
2020-08-31 10:31:40.413 [error] <0.1175.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor' had child 'Elixir.Engine.AdminProcessor.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Engine.AdminProcessor.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1308.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:40.413 [error] <0.539.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79072> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.Engine.AdminProcessor.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.1175.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:40.413 [error] <0.539.0> Supervisor 'Elixir.Engine.AdminProcessor.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79072> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.Engine.AdminProcessor.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.Engine.AdminProcessor.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.1175.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:40.414 [error] <0.487.0> Supervisor 'Elixir.Engine.Supervisor' had child 'Elixir.Engine.AdminProcessor' started with 'Elixir.Engine.AdminProcessor':start_link([]) at <0.538.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:45.895 [error] <0.654.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1467.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.654.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:45.896 [error] <0.654.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1467.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.654.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:45.896 [error] <0.653.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.654.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1467.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.654.0>},60000]}} in context child_terminated
2020-08-31 10:31:45.946 [error] <0.1469.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1481.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1469.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:45.946 [error] <0.1469.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1481.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1469.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:45.946 [error] <0.653.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1469.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1481.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1469.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.003 [error] <0.1483.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1495.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1483.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.004 [error] <0.1483.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1495.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1483.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.004 [error] <0.653.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1483.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1495.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1483.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.004 [error] <0.653.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1483.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:46.005 [error] <0.652.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79116> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.653.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:46.061 [error] <0.1498.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1562.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1498.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.062 [error] <0.1498.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1562.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1498.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.063 [error] <0.1497.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1498.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1562.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1498.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.132 [error] <0.1564.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1576.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1564.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.133 [error] <0.1564.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1576.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1564.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.133 [error] <0.1497.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1564.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1576.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1564.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.191 [error] <0.1578.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1590.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1578.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.192 [error] <0.1578.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1590.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1578.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.192 [error] <0.1497.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1578.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1590.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1578.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.193 [error] <0.1497.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1578.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:46.193 [error] <0.652.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79116> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.1497.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:46.248 [error] <0.1593.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1657.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1593.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.248 [error] <0.1593.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1657.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1593.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.249 [error] <0.1592.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1593.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1657.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1593.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.297 [error] <0.1659.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1671.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1659.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.298 [error] <0.1659.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1671.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1659.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.299 [error] <0.1592.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1659.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1671.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1659.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.348 [error] <0.1673.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1685.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1673.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.350 [error] <0.1673.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1685.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1673.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.350 [error] <0.1592.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1673.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1685.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1673.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.350 [error] <0.1592.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1673.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:46.350 [error] <0.652.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79116> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.1592.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:46.425 [error] <0.1688.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1752.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1688.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.425 [error] <0.1688.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1752.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1688.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.426 [error] <0.1687.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1688.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1752.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1688.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.476 [error] <0.1754.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1766.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1754.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.477 [error] <0.1754.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1766.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1754.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.479 [error] <0.1687.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1754.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1766.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1754.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.525 [error] <0.1768.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1780.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1768.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.525 [error] <0.1768.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1780.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1768.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.526 [error] <0.1687.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1768.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1780.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1768.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.526 [error] <0.1687.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1768.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:46.526 [error] <0.652.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79116> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.1687.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:46.527 [error] <0.652.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.79116> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.1687.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:46.527 [error] <0.487.0> Supervisor 'Elixir.Engine.Supervisor' had child 'Elixir.BookingRoutes' started with 'Elixir.BookingRoutes':start_link([]) at <0.651.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:46.580 [error] <0.1785.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1849.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1785.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.582 [error] <0.1785.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1849.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1785.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.582 [error] <0.1784.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1785.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1849.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1785.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.633 [error] <0.1851.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1863.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1851.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.634 [error] <0.1851.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1863.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1851.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.635 [error] <0.1784.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1851.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1863.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1851.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.695 [error] <0.1865.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1877.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1865.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.696 [error] <0.1865.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1877.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1865.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:46.697 [error] <0.1784.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1865.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.1877.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.1865.0>},60000]}} in context child_terminated
2020-08-31 10:31:46.697 [error] <0.1784.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.1865.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:47.015 [error] <0.2136.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2148.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2136.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.016 [error] <0.2136.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2148.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2136.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.017 [error] <0.2069.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2136.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2148.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2136.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.059 [error] <0.2150.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2162.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2150.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.060 [error] <0.2150.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2162.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2150.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.060 [error] <0.2069.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2150.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2162.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2150.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.060 [error] <0.2069.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2150.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:47.060 [error] <0.1783.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.82675> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2069.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:47.061 [error] <0.1783.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486789.82675> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2069.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:47.061 [error] <0.487.0> Supervisor 'Elixir.Engine.Supervisor' had child 'Elixir.BookingRoutes' started with 'Elixir.BookingRoutes':start_link([]) at <0.1782.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:47.111 [error] <0.2167.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2231.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2167.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.112 [error] <0.2167.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2231.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2167.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.112 [error] <0.2166.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2167.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2231.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2167.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.164 [error] <0.2233.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2245.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2233.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.165 [error] <0.2233.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2245.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2233.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.166 [error] <0.2166.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2233.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2245.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2233.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.220 [error] <0.2247.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2259.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2247.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.221 [error] <0.2247.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2259.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2247.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.221 [error] <0.2166.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2247.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2259.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2247.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.222 [error] <0.2166.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2247.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:47.222 [error] <0.2165.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486788.80847> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2166.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:47.288 [error] <0.2262.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2326.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2262.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.290 [error] <0.2262.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2326.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2262.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.290 [error] <0.2261.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2262.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2326.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2262.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.338 [error] <0.2328.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2340.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2328.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.339 [error] <0.2328.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2340.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2328.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.339 [error] <0.2261.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2328.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2340.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2328.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.381 [error] <0.2342.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2354.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2342.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.382 [error] <0.2342.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2354.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2342.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.382 [error] <0.2261.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2342.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2354.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2342.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.383 [error] <0.2261.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2342.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:47.383 [error] <0.2165.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486788.80847> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2261.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:47.435 [error] <0.2357.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2421.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2357.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.436 [error] <0.2357.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2421.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2357.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.437 [error] <0.2356.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2357.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2421.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2357.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.491 [error] <0.2423.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2435.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2423.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.493 [error] <0.2423.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2435.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2423.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.493 [error] <0.2356.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2423.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2435.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2423.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.543 [error] <0.2437.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2449.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2437.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.543 [error] <0.2437.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2449.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2437.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.543 [error] <0.2356.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2437.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2449.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2437.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.544 [error] <0.2356.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2437.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:47.544 [error] <0.2165.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486788.80847> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2356.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:47.595 [error] <0.2452.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2516.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2452.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.596 [error] <0.2452.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2516.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2452.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.596 [error] <0.2451.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2452.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2516.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2452.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.643 [error] <0.2518.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2530.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2518.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.645 [error] <0.2518.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2530.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2518.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.646 [error] <0.2451.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2518.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2530.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2518.0>},60000]}} in context child_terminated
2020-08-31 10:31:47.694 [error] <0.2532.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2544.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2532.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:47.694 [error] <0.2532.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2544.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2532.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.035 [error] <0.2805.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2817.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2805.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.036 [error] <0.2805.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2817.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2805.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.036 [error] <0.2738.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2805.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2817.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2805.0>},60000]}} in context child_terminated
2020-08-31 10:31:48.086 [error] <0.2819.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2831.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2819.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.087 [error] <0.2819.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2831.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2819.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.088 [error] <0.2738.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2819.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2831.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2819.0>},60000]}} in context child_terminated
2020-08-31 10:31:48.088 [error] <0.2738.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2819.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:48.088 [error] <0.2547.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486788.81326> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2738.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:48.137 [error] <0.2834.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2898.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2834.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.137 [error] <0.2834.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2898.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2834.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.138 [error] <0.2833.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2834.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2898.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2834.0>},60000]}} in context child_terminated
2020-08-31 10:31:48.183 [error] <0.2900.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2912.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2900.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.184 [error] <0.2900.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2912.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2900.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.185 [error] <0.2833.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2900.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2912.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2900.0>},60000]}} in context child_terminated
2020-08-31 10:31:48.227 [error] <0.2914.0> gen_server 'Elixir.BookingRoutes.Broadway.Producer_0' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2926.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2914.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.228 [error] <0.2914.0> CRASH REPORT Process 'Elixir.BookingRoutes.Broadway.Producer_0' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2926.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2914.0>},60000]}} in gen_server:call/3 line 223
2020-08-31 10:31:48.228 [error] <0.2833.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2914.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'incoming_booking_updates' in vhost '/'">>}},{gen_server,call,[<0.2926.0>,{call,{'queue.bind',0,<<"add_route_to_booking_object">>,<<"incoming_booking_updates">>,<<"registered">>,false,[]},none,<0.2914.0>},60000]}} in context child_terminated
2020-08-31 10:31:48.228 [error] <0.2833.0> Supervisor 'Elixir.BookingRoutes.Broadway.ProducerSupervisor' had child 'Elixir.BookingRoutes.Broadway.Producer_0' started with 'Elixir.Broadway.Producer':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingRoutes.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.2914.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:48.228 [error] <0.2547.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486788.81326> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2833.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:48.229 [error] <0.2547.0> Supervisor 'Elixir.BookingRoutes.Broadway.Supervisor' had child #Ref<0.2939961136.3194486788.81326> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.BookingRoutes.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Producer',...}}], [{name,'Elixir.BookingRoutes.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at <0.2833.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 10:31:48.229 [error] <0.487.0> Supervisor 'Elixir.Engine.Supervisor' had child 'Elixir.BookingRoutes' started with 'Elixir.BookingRoutes':start_link([]) at <0.2546.0> exit with reason shutdown in context child_terminated
2020-08-31 10:31:48.229 [error] <0.487.0> Supervisor 'Elixir.Engine.Supervisor' had child 'Elixir.BookingRoutes' started with 'Elixir.BookingRoutes':start_link([]) at <0.2546.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:28:39.130 [error] <0.418.0> gen_server <0.418.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.130 [error] <0.436.0> gen_server <0.436.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.130 [error] <0.661.0> gen_server <0.661.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.619.0> gen_server <0.619.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.530.0> gen_server <0.530.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.401.0> gen_server <0.401.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.414.0> gen_server <0.414.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.432.0> gen_server <0.432.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.614.0> gen_server <0.614.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.496.0> gen_server <0.496.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.657.0> gen_server <0.657.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.395.0> gen_server <0.395.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:28:39.131 [error] <0.432.0> CRASH REPORT Process <0.432.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:28:39.132 [error] <0.414.0> CRASH REPORT Process <0.414.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:28:39.132 [error] <0.412.0> Supervisor {<0.412.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.413.0>, {amqp_params_network,<<"guest">>,<<"Gk0pP7yPenPDq+renUyFC7HIV0ygBdr7KB4fSqHEtn5QhMxVWUfYGvltIAeOFu...">>,...}) at <0.414.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:28:39.132 [error] <0.430.0> Supervisor {<0.430.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.431.0>, {amqp_params_network,<<"guest">>,<<"5IOTXPIhTdhqWAYtkVsIMZSEHvmgkyg6jSgiyfVc/yVnb24hB3oC47crVkcPHg...">>,...}) at <0.432.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:28:39.132 [error] <0.412.0> Supervisor {<0.412.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.413.0>, {amqp_params_network,<<"guest">>,<<"Gk0pP7yPenPDq+renUyFC7HIV0ygBdr7KB4fSqHEtn5QhMxVWUfYGvltIAeOFu...">>,...}) at <0.414.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:28:39.133 [error] <0.430.0> Supervisor {<0.430.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.431.0>, {amqp_params_network,<<"guest">>,<<"5IOTXPIhTdhqWAYtkVsIMZSEHvmgkyg6jSgiyfVc/yVnb24hB3oC47crVkcPHg...">>,...}) at <0.432.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:28:39.133 [error] <0.657.0> CRASH REPORT Process <0.657.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:28:39.133 [error] <0.614.0> CRASH REPORT Process <0.614.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:28:39.133 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:28:39.133 [error] <0.395.0> CRASH REPORT Process <0.395.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:28:39.133 [error] <0.655.0> Supervisor {<0.655.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.656.0>, {amqp_params_network,<<"guest">>,<<"fh0RPTcJwqlHMBwOMgQS+6PvXnJfwA4SneQo3gwLJblQWlMDu4gBPfKES9DYFy...">>,...}) at <0.657.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:28:39.133 [error] <0.655.0> Supervisor {<0.655.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.656.0>, {amqp_params_network,<<"guest">>,<<"fh0RPTcJwqlHMBwOMgQS+6PvXnJfwA4SneQo3gwLJblQWlMDu4gBPfKES9DYFy...">>,...}) at <0.657.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:28:39.134 [error] <0.612.0> Supervisor {<0.612.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.613.0>, {amqp_params_network,<<"guest">>,<<"Zf2FbyA3C8dm/dMLyRNy3WjLREqStHhv99cXkY6HHbYtRcOax3HBgmPbdgQpcM...">>,...}) at <0.614.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:28:39.134 [error] <0.612.0> Supervisor {<0.612.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.613.0>, {amqp_params_network,<<"guest">>,<<"Zf2FbyA3C8dm/dMLyRNy3WjLREqStHhv99cXkY6HHbYtRcOax3HBgmPbdgQpcM...">>,...}) at <0.614.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:28:39.134 [error] <0.492.0> Supervisor {<0.492.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.493.0>, {amqp_params_network,<<"guest">>,<<"TjZgdChDJRj03OyODfaUVYTq/jlfptPsZrH7eWjFj2B1BTchT8X6fGbJtN0Th7...">>,...}) at <0.496.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:28:39.134 [error] <0.492.0> Supervisor {<0.492.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.493.0>, {amqp_params_network,<<"guest">>,<<"TjZgdChDJRj03OyODfaUVYTq/jlfptPsZrH7eWjFj2B1BTchT8X6fGbJtN0Th7...">>,...}) at <0.496.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:28:39.135 [error] <0.393.0> Supervisor {<0.393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.394.0>, {amqp_params_network,<<"guest">>,<<"J3YHPZZIyFhH7B3eB2LFFjH58zzoMhAo67VUFrlorNjX9Ut6UUUHVDR095j1T8...">>,...}) at <0.395.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:28:39.135 [error] <0.393.0> Supervisor {<0.393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.394.0>, {amqp_params_network,<<"guest">>,<<"J3YHPZZIyFhH7B3eB2LFFjH58zzoMhAo67VUFrlorNjX9Ut6UUUHVDR095j1T8...">>,...}) at <0.395.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:53:16.824 [error] <0.800.0> gen_server <0.800.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:53:16.824 [error] <0.793.0> gen_server <0.793.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:53:16.824 [error] <0.800.0> CRASH REPORT Process <0.800.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:53:16.825 [error] <0.793.0> CRASH REPORT Process <0.793.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:53:16.825 [error] <0.801.0> gen_server <0.801.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:53:16.825 [error] <0.792.0> Supervisor {<0.792.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.18>, <0.793.0>, <0.796.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:53302 -> 127.0.0.1:5672">>) at <0.800.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:53:16.825 [error] <0.801.0> CRASH REPORT Process <0.801.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:53:16.825 [error] <0.792.0> Supervisor {<0.792.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.18>, <0.793.0>, <0.796.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:53302 -> 127.0.0.1:5672">>) at <0.800.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:53:16.826 [error] <0.790.0> gen_server <0.790.0> terminated with reason: {socket_error,timeout}
2020-08-31 18:53:16.826 [error] <0.791.0> Supervisor {<0.791.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.792.0>, {amqp_params_network,<<"guest">>,<<"70BcpUobjjB8AjPvNZ6T/DgJRwS/2fcn7kWTeKV8LtroWrhazqUnVKxsvIHa/T...">>,...}) at <0.793.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:53:16.826 [error] <0.790.0> CRASH REPORT Process <0.790.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-08-31 18:53:16.826 [error] <0.791.0> Supervisor {<0.791.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.792.0>, {amqp_params_network,<<"guest">>,<<"70BcpUobjjB8AjPvNZ6T/DgJRwS/2fcn7kWTeKV8LtroWrhazqUnVKxsvIHa/T...">>,...}) at <0.793.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:53:16.826 [error] <0.789.0> Supervisor {<0.789.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.17>, <0.790.0>, <0.797.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:53301 -> 127.0.0.1:5672">>) at <0.801.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:53:16.827 [error] <0.789.0> Supervisor {<0.789.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.17>, <0.790.0>, <0.797.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:53301 -> 127.0.0.1:5672">>) at <0.801.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-31 18:53:16.827 [error] <0.788.0> Supervisor {<0.788.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.789.0>, {amqp_params_network,<<"guest">>,<<"RVbwFCfG2mGr6D3QWxfnOSoxGsk/tsgszSnpUswfq5bC3oQBgZkrwnlq/Ukm89...">>,...}) at <0.790.0> exit with reason {socket_error,timeout} in context child_terminated
2020-08-31 18:53:16.827 [error] <0.788.0> Supervisor {<0.788.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.789.0>, {amqp_params_network,<<"guest">>,<<"RVbwFCfG2mGr6D3QWxfnOSoxGsk/tsgszSnpUswfq5bC3oQBgZkrwnlq/Ukm89...">>,...}) at <0.790.0> exit with reason reached_max_restart_intensity in context shutdown
